version: '3.8'

services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  productdb:
    image: mysql:8.0.29
  
  customerdb:
    image: postgres:alpine3.16
    
  basketdb:
    image: redis:alpine

  inventorydb:
    image: mongo

  #infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
  #microservices api section
  product.api: # Tên service trong docker compose
    # Cấu hình image name theo format
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    # ${DOCKER_REGISTRY-} : Registry để push/pull image, nếu không set thì để trống
    # product-api : Tên của image
    # ${PLATFORM:-linux} : Platform đang sử dụng, mặc định là linux nếu không set
    # ${TAG:-latest} : Version tag của image, mặc định là latest nếu không set
    build:
      context: . # Build context là thư mục gốc (root) của project
      dockerfile: Services/Product.API/Dockerfile # Đường dẫn tới Dockerfile của service

#network section
networks:
  default:
    name: GenZ_microservices
    driver: bridge

#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: postgres_data
  portainer_data:
    name: portainer_data
  elasticsearch_data:
    name: elasticsearch_data
  jaeger_data:
    name: jaeger_data
  mongo_data:
    name: mongo_data
  pgadmin_data:
    name: pgadmin_data
